CREATE TABLE IF NOT EXISTS USER (
  ID VARCHAR(20) PRIMARY KEY,
  NAME VARCHAR(20),
  PASSWORD VARCHAR(200)
);


CREATE TABLE IF NOT EXISTS BOARD (
  ID VARCHAR(20) PRIMARY KEY,
  TITLE VARCHAR(20),
  CONTENTS VARCHAR(200),
  REG_ID VARCHAR(20),
  REG_DATE DATE
);