DELETE FROM USER WHERE ID = 'test';
INSERT INTO USER (ID, NAME, PASSWORD) VALUES ('test', '테스트', 'test');

DELETE FROM BOARD WHERE ID = '1';
INSERT INTO BOARD (ID, TITLE, CONTENTS, REG_ID, REG_DATE) VALUES ('1', '테스트', '테스트내용', 'test', '2020-09-08');